### ISSUE TITLE
Missing "workspace" control panel for LVV

### ISSUE THREAD

**Issue by freshpomelo** [JaneliaSciComp/workstation#4]
Hi everyone,

I would like to use LVV to display and trace neuron of octree tiff data.
In "pen mode", when I tried to SHIFT+click the image, the error message displayed:
<img width="1413" alt="workspace error" src="https://user-images.githubusercontent.com/10544528/71540330-f371d680-2983-11ea-9335-5e3a6f60b2af.png">

And the "workspace" control is missing at the top of the editor panel, which should be there following the instruction of "Janelia Workstation User Manual".

**Comment by olbris** [comment]
It looks to me as if you're using the Janelia workstation on a display that doesn't have a lot of vertical resolution. In those cases, not all of the components in the right-hand panel will fit, and some will be missing. Usually the top and bottom components go first.

You may be able to reclaim some space by closing the toolbars at the top of the workstation (View menu, then choose Toolbars). It may not show all of the workspace info panel, but all you need to see is the "+" button in order to create a workspace from the sample (which will solve the problem shown in the error dialog).
